name: LiveUnicode_CI


on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.11'

    - name: Cache Julia packages
      uses: actions/cache@v3
      with:
        path: ~/.julia/artifacts
        key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-

    - name: Install dependencies
      run: julia --project -e 'using Pkg; Pkg.instantiate()'

    - name: Run unit tests
      run: julia --project -e 'using Pkg; Pkg.test()'